"""initial_schema

Revision ID: 6a69a1c21f43
Revises: 
Create Date: 2026-08-17 16:55:14.299419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a69a1c21f43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_last_active_at'), 'sessions', ['last_active_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('request_message', sa.Text(), nullable=False),
    sa.Column('gate_1_action', sa.Enum('SOFT_ASK', 'PROCEED', name='gate_1_action_enum'), nullable=True),
    sa.Column('gate_1_rationale', sa.Text(), nullable=True),
    sa.Column('gate_2_action', sa.Enum('ANSWER', 'GENERALIZE', 'ABSTAIN', 'ESCALATE', name='gate_2_action_enum'), nullable=True),
    sa.Column('gate_2_rationale', sa.Text(), nullable=True),
    sa.Column('final_action', sa.Enum('SOFT_ASK', 'ANSWER', 'GENERALIZE', 'ABSTAIN', 'ESCALATE', name='final_action_enum'), nullable=False),
    sa.Column('evidence_chunk_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_table('clinical_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('BP_READING', 'MEDICATION_ADDED', 'MEDICATION_STOPPED', 'SYMPTOM_REPORTED', 'DEMOGRAPHIC', 'LAB_RESULT', name='event_type_enum'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_clinical_events_session_id'), 'clinical_events', ['session_id'], unique=False)
    op.create_table('context_snapshots',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('soft_ask_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('message_history',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('action', sa.Enum('SOFT_ASK', 'ANSWER', 'GENERALIZE', 'ABSTAIN', 'ESCALATE', name='final_action_enum'), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_message_history_session_id'), 'message_history', ['session_id'], unique=False)
    # ### end Alembic commands ###

    # Add immutability rules for append-only tables
    op.execute('''
    CREATE RULE no_update_events AS ON UPDATE TO clinical_events
    DO INSTEAD NOTHING;
    ''')
    op.execute('''
    CREATE RULE no_delete_events AS ON DELETE TO clinical_events
    DO INSTEAD NOTHING;
    ''')
    op.execute('''
    CREATE RULE no_update_audit AS ON UPDATE TO audit_logs
    DO INSTEAD NOTHING;
    ''')
    op.execute('''
    CREATE RULE no_delete_audit AS ON DELETE TO audit_logs
    DO INSTEAD NOTHING;
    ''')


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('DROP RULE IF EXISTS no_delete_audit ON audit_logs;')
    op.execute('DROP RULE IF EXISTS no_update_audit ON audit_logs;')
    op.execute('DROP RULE IF EXISTS no_delete_events ON clinical_events;')
    op.execute('DROP RULE IF EXISTS no_update_events ON clinical_events;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_history_session_id'), table_name='message_history')
    op.drop_table('message_history')
    op.drop_table('context_snapshots')
    op.drop_index(op.f('ix_clinical_events_session_id'), table_name='clinical_events')
    op.drop_table('clinical_events')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_sessions_last_active_at'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
    
    # Clean up enum types
    op.execute('DROP TYPE IF EXISTS event_type_enum;')
    op.execute('DROP TYPE IF EXISTS final_action_enum;')
    op.execute('DROP TYPE IF EXISTS gate_2_action_enum;')
    op.execute('DROP TYPE IF EXISTS gate_1_action_enum;')
