from enum import StrEnum

class ActionEnum(StrEnum):
    SOFT_ASK = "SOFT-ASK"
    ANSWER = "ANSWER"
    GENERALIZE = "GENERALIZE"
    ABSTAIN = "ABSTAIN"
    ESCALATE = "ESCALATE"

class EventTypeEnum(StrEnum):
    BP_READING = "BP_READING"
    MEDICATION_ADDED = "MEDICATION_ADDED"
    MEDICATION_STOPPED = "MEDICATION_STOPPED"
    SYMPTOM_REPORTED = "SYMPTOM_REPORTED"
    DEMOGRAPHIC = "DEMOGRAPHIC"
    LAB_RESULT = "LAB_RESULT"
